// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnDejCF0M6l83DXjUstrprtmWxobCseG0',
    appId: '1:89059391038:web:2f63844ffb6ac1c598436f',
    messagingSenderId: '89059391038',
    projectId: 'habits-uas',
    authDomain: 'habits-uas.firebaseapp.com',
    storageBucket: 'habits-uas.firebasestorage.app',
    measurementId: 'G-7J8N1L4PLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2-dOGV4vRu6LnJIMOiLW6AGVB7h5SdhA',
    appId: '1:89059391038:android:017f28ff5d54259a98436f',
    messagingSenderId: '89059391038',
    projectId: 'habits-uas',
    storageBucket: 'habits-uas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMhEf5W0rMHotMhBEjGuCJcBcIsxCUcg',
    appId: '1:89059391038:ios:e31048aaf6f225d598436f',
    messagingSenderId: '89059391038',
    projectId: 'habits-uas',
    storageBucket: 'habits-uas.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUasProductivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiMhEf5W0rMHotMhBEjGuCJcBcIsxCUcg',
    appId: '1:89059391038:ios:e31048aaf6f225d598436f',
    messagingSenderId: '89059391038',
    projectId: 'habits-uas',
    storageBucket: 'habits-uas.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUasProductivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnDejCF0M6l83DXjUstrprtmWxobCseG0',
    appId: '1:89059391038:web:c9cca9a55963b54d98436f',
    messagingSenderId: '89059391038',
    projectId: 'habits-uas',
    authDomain: 'habits-uas.firebaseapp.com',
    storageBucket: 'habits-uas.firebasestorage.app',
    measurementId: 'G-SKCC9X9NCG',
  );
}
